# Cloud Build configuration for automated deployment
# This file is used by Google Cloud Build to build and deploy the application

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/agenda-cal:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/agenda-cal:latest'
      - '.'
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/agenda-cal:$COMMIT_SHA'
    id: 'push-image-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/agenda-cal:latest'
    id: 'push-image-latest'
    waitFor: ['build-image']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'agenda-cal-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/agenda-cal:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--cpu'
      - '2'
      - '--memory'
      - '1Gi'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--add-cloudsql-instances'
      - '${_CLOUDSQL_INSTANCE}'
      - '--set-env-vars'
      - 'TZ=${_TZ}'
    id: 'deploy-cloud-run'
    waitFor: ['push-image-sha', 'push-image-latest']

# Substitution variables (can be overridden in trigger or command line)
substitutions:
  _REGION: 'us-central1'
  _CLOUDSQL_INSTANCE: '${PROJECT_ID}:${_REGION}:agenda-cal-db'
  _TZ: 'America/Sao_Paulo'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/agenda-cal:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/agenda-cal:latest'

# Build timeout
timeout: '1200s'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

